version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: false
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Install Puppeteer dependencies (for headless Chrome)
          command: |
            sudo apt-get update
            sudo apt-get install -yq --no-install-recommends \
              ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
              libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 libx11-xcb1 \
              libxcomposite1 libxdamage1 libxrandr2 xdg-utils
      - run:
          name: Run tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-node
    # - deploy:
    #     requires:
    #       - test-node
